# Generated by Django 4.1 on 2022-09-29 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_member'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='BetGroup',
        ),
    ]
